language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
    - vendor/bin/phpstan analyse --level=max src
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
